add-reviews
ansstey/project-YachtJet-22 pull request #3
Opened 2024-08-08 22:24 UTC by Oksana1285

2024-08-08 22:50 UTC, ansstey commented on src/css/reviews.css
> +  .reviews-item-ihor {
display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 24px;
    background: #fbfbfb;
    
Повторюються ці характеристики для .reviews-item-ihor, .reviews-item-victoria, .reviews-item-john. Можна винести це в загальний клас .reviews-item для облегшення коду, а окремі імена лишити вже для відображень на різних пристроях (display: none і тд)

2024-08-08 22:52 UTC, ansstey commented on src/css/reviews.css
> +  padding: 32px 8px;
padding 32 28
![image](https://github.com/user-attachments/assets/46c4667d-ee9b-4baa-bcb9-e527e228ceee)

2024-08-08 22:59 UTC, ansstey commented on src/css/reviews.css
> +.reviews-image {
![image](https://github.com/user-attachments/assets/6bab7003-ca4f-4d37-a1c9-abe0d3ded90c)
![image](https://github.com/user-attachments/assets/7d6473f6-53d4-404d-b08c-ce5291eeaac7)
![image](https://github.com/user-attachments/assets/ed812ba1-9471-46ed-b066-209d951e03fb)

Перекинути марджини з тексту, на картинку. Картинка займає свою ширину, потім відступ до тексту, текст займає свою ширину. В макеті це виглядає як послідовні блоки, а не вирване зображення зверху

2024-08-08 23:03 UTC, ansstey requested changes
З того, що помітила виділила кілька моментів. 
Ще в десктопній версії занадто великий відступ між фото та текстом, скоріше за все виправиться, якщо налаштувати блок картинка (зайняла висоту, ширину), наступний текст, зайняв свою ширину, висоту

2024-08-09 05:58 UTC, Oksana1285 commented
Внесла зміни, перегляньте будь ласка

2024-08-09 06:56 UTC, ansstey requested changes
1) 
![image](https://github.com/user-attachments/assets/3ce9fce6-9103-401a-a185-37d943c00a8b)
![image](https://github.com/user-attachments/assets/e5d9f099-aacb-4d0e-bdb9-720bc7788b21)
![image](https://github.com/user-attachments/assets/04539ec1-74c5-4ddf-ad78-366126730a1d)
Де в тексту верхній margin, потрібні бокові у picture чи img
2) 
![image](https://github.com/user-attachments/assets/2fcba2a8-5734-4406-b109-da6f569c4f85)
Злітає центрування тексту в картці при зміні ширини

2024-08-09 19:43 UTC, ansstey requested changes
![image](https://github.com/user-attachments/assets/b7ed1306-1e21-479d-ab28-4704583a52f7)
1) На мобільній версії відсутній відступ між текстом і карткою в 40px
2) Не задана максимальна ширина картки(335), через що вона розповзається на весь екран
3) Лишається проблема із накладанням фото поверх чужого марджина -> 
![image](https://github.com/user-attachments/assets/aeb85816-8b5c-4aba-b850-434e5d863bfa)
![image](https://github.com/user-attachments/assets/825f2c11-d77f-4054-b734-9b6e9a5d3901)
Тут в ролі флекса йде і ul, і **li** (сама картка), тоді як h3 та  p це елементи всередині флекс-боксу, яким хіба-що малий марджин додати

2024-08-09 20:17 UTC, Oksana1285 commented
Ніби виправила

2024-08-09 21:08 UTC, Oksana1285 commented
+

2024-08-09 21:24 UTC, ansstey requested changes
Картки працюють, трошки з'їхав заголовок. Додати 
**.reviews-container** {
  display: flex;
    flex-direction: column;
    align-items: center;
}

max-width: 501px; для **reviews-text** для планшетів та 571 для десктопу

Плюс margin-bottom для всіх версій на **reviews-text** та **reviews-title**

2024-08-10 07:09 UTC, Oksana1285 commented
Внесла правки

2024-08-10 08:29 UTC, ansstey commented on src/css/reviews.css
> +  background-color: blue;
Трошки інший колір та має йти від файлу common.css

2024-08-10 08:30 UTC, ansstey commented on src/partials/reviews.html
> +              src="../img/reviews/victoria-desk-2x.jpg"
При злитті запит буде йти від index.html, достатньо однієї крапки, або як і було без крапок взагалі

2024-08-10 08:30 UTC, ansstey requested changes
Прибрати блакитний колір бекграунду та крапки у шляхах, все інше супер!

2024-08-10 11:48 UTC, Oksana1285 commented on src/css/reviews.css
> +  background-color: blue;
Колір додавала, щоб бачити відступи. І забула забрати. Вибачте

2024-08-10 11:48 UTC, Oksana1285 commented
Змінила

2024-08-10 20:29 UTC, ansstey commented
> Змінила

![image](https://github.com/user-attachments/assets/3b434e27-d89b-47d9-95a5-e47c33bc1b2e)
Не відобразився реквест, тільки попередня версія

2024-08-10 20:36 UTC, ansstey approved these changes

2024-08-10 20:36 UTC, merged